#!/bin/sh /etc/rc.common
# Copyright (C) 2013 NXP Semiconductor

START=97

PROG=zigbee_daemon


start () {
	ln -s lock /var/run/zigbee_daemon.lock || exit 0
	if [ -x /bin/zigbee_daemon ]; then
		$PROG -s /dev/ttyS0 -B 230400 -D /etc/config/Zigbee.DB -v 3 -g
		ES=$?
		[ "$VERBOSE" != no ] && echo $ES
		return $ES
	fi
}


stop () {
	ps | grep zigbee_daemon | grep D | awk '{print $1}'  | xargs kill -9
	rm -rf /var/run/zigbee_daemon.lock
}

status () {
	ps | grep zigbee_daemon | grep D
}