#!/bin/sh /etc/rc.common
# Copyright (C) 2013 NXP Semiconductor

START=97

PROG=zigbee_daemon


start () {
    $PROG -s /dev/ttyS0 -B 115200 -D /etc/config/Zigbee.DB
}


stop () {
    killall $PROG
}

